### ISSUE TITLE
Provide defaults for using JAVA_HOME cacerts for proxy / client creation

### ISSUE THREAD

**Issue by dotCipher** [palantir/conjure-java-runtime#145] opened 2016-06-25 17:55 UTC
There are cases where we may just want to use the trusted certs from the default `cacerts` file from `JAVA_HOME` when no `Optional<SSLSocketFactory` is provided.

Not exactly sure where the best spot to put the default would be, or if we should be making it more explicit?

A few options I see are as follows:
- Adding an `else` after the `ClientProvider` classes (ie. https://github.com/palantir/http-remoting/blob/develop/http-clients/src/main/java/com/palantir/remoting/http/FeignClientFactory.java#L229) that pulls the java home cacerts location
- Create new method signatures (ie. `createProxyWithCaCerts(..)` or something along those lines)

Thoughts?

**Comment by uschi2000** [comment] 2016-06-25 18:09
I haven't confirmed this empirically, but I would have expected OkHttp to
use the Java default certs/sslsocketfactory if none is explicitly provided?

**Comment by dotCipher** [comment] 2016-06-25 18:55
Hmm good point, [it looks like it does at quick glance](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/OkHttpClient.java#L185), but I will attach a debugger and see what I can find.

**Comment by dotCipher** [comment] 2016-06-27 19:57
I poked around a bit and it seems like the implementation that OkHttp uses for grabbing the SSLContext uses an impl of the `TrustManagerFactoryImpl` that uses the `jssecacerts` file first before the `cacerts` file.

From `TrustManagerFactoryImpl`:

```
var2 = new File(var9 + var7 + "lib" + var7 + "security" + var7 + "jssecacerts");
                    if((var3 = getFileInputStream(var2)) == null) {
                        var2 = new File(var9 + var7 + "lib" + var7 + "security" + var7 + "cacerts");
                        var3 = getFileInputStream(var2);
                    }
```

Which means that if we follow the standard directions of trusting the Palantir CA in our `cacerts` file we end up not being able to get the appropriate trust chain.

I handled this by removing the `jssecacerts` file on my local machine, but I am not sure about this kind of guarantee on Circle, etc.  What do you think the best way to handle this would be?

**Comment by uschi2000** [comment] 2016-06-27 20:02
This priority seems to be correct w.r.t. to Java spec:
http://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/JSSERefGuide.html#X509TrustManager

**Comment by dotCipher** [comment] 2016-06-27 20:06
Not sure if I should do a workaround of explicitly using the `cacerts` file on my end when that priority order is the standard.  Shouldn't our circle nodes have the third gen root CA trusted then (under `jssecacerts` if it exists)?

**Comment by uschi2000** [comment] 2016-06-27 21:02
closing after some offline discussion.

**Closed as completed by uschi2000** 2016-06-27 21:02 UTC
