### ISSUE TITLE
Optional<String> is not serialized as JSON when the content type is application/json

### ISSUE THREAD

**Issue by leeavital** [palantir/conjure-java-runtime#131] opened 2016-06-07 19:48 UTC
```
interface MyService {
  @GET
  @Produces(APPLICATION_JSON);
  Optional<String> ping();
}


MyResource implements MyService {
    @Override
    Optional <String> ping() {
          return "pong";
    }
}

```

`curl $URL/ping` gives you  `pong`, but it should give you `"pong"` (with quotes)

**Comment by leeavital** [comment] 2016-06-09 21:08
After some more investigation it looks like this is an issue in dropwizard, and not in http-remoting. Some options are:
- Try and fix this upstream in dropwizard (it's unclear if this was intentional)
- Make http-remoting's decoder work when a string is unquoted

**Comment by markelliot** [comment] 2016-06-09 21:13
Could you elaborate a bit on the Dropwizard bug, not sure I’m following.

**Comment by leeavital** [comment] 2016-06-15 16:58
Starting with a vanilla dropwizard app, if I have a service like:

```
@GET
@Produces(JSON)
@Path("/ping")
String ping() {
  return "pong";
}
```

Curling ping will give you a response with the response body: `pong`. This is invalid JSON -- it should be `"pong"`.

The problem is exacerbated when http-remoting tries to decode json -- you'll get a message like `"unexpected token, "p", expected ..."`

**Comment by markelliot** [comment] 2016-06-15 17:02
Sorry, you said "try to fix this upstream in dropwizard", is it actually a dropwizard issue?

**Comment by leeavital** [comment] 2016-06-15 17:09
I believe it's either jersey, or dropwizard misconfiguring jersey in some way.

_but_ we could fix it in http-remoting with custom encoders and not force users to upgrade to the latest $upstream_library

**Comment by markelliot** [comment] 2016-06-15 17:11
Would prefer to fix in Dropwizard or Jersey rather than work around it.

**Comment by henryptung** [comment] 2016-07-13 23:14
Last comment of https://github.com/dropwizard/dropwizard/issues/231 seems very relevant.

Also, FWIW, the `_untouchables` set is a mutable static public (as are some other collections in that class). 😈

**Comment by markelliot** [comment] 2017-01-03 15:09
given that this is a pragmatic Jersey decision, going to say this is intended behavior and close this.

**Closed as completed by markelliot** 2017-01-03 15:09 UTC
