### ISSUE TITLE
okhttp clients does not declare dependency on JaxRS

### ISSUE THREAD

**Issue by gatesn** [palantir/conjure-java-runtime#594] opened 2017-10-30 10:24 UTC
https://github.com/palantir/http-remoting/blob/d1e472729a8eb71c93a5bfdaf8c761a2c493e799/okhttp-clients/src/main/java/com/palantir/remoting3/okhttp/metrics/HostMetrics.java#L42

This therefore doesn't raise as a version conflict, and I'm getting a runtime NoSuchMethod exception:

```
Caused by: java.lang.NoSuchMethodError: javax.ws.rs.core.Response$Status$Family.familyOf(I)Ljavax/ws/rs/core/Response$Status$Family;
	at com.palantir.remoting3.okhttp.metrics.HostMetrics.record(HostMetrics.java:42)
	at com.palantir.remoting3.okhttp.metrics.HostMetricsRegistry.record(HostMetricsRegistry.java:48)
```

**Comment by uschi2000** [comment] 2017-10-30 15:16
I'm pretty sure this project has a transitive dependency on ws.rs through the `error-handling` dependency.

**Comment by justinuang** [comment] 2017-11-03 16:53
To clarify, the actual issue is that we depend on jersey-core:1.9 transitively through hadoop, which packages some of the classes declared in javax.ws.rs:javax.ws.rs-api. The Response$Status$Family class provided in jersey-core doesn't have the familyOf method.

Unfortunately, I don't think we have a choice regarding the jersey-core dependency since it's still in the latest hadoop here: https://hadoop.apache.org/docs/r2.8.2/hadoop-project-dist/hadoop-hdfs/dependency-analysis.html

Could we try inlining that method and see if it fixes our build? The hypothesis is that jersey-core brings in classes that are roughly the same, but only differ on a small subset of methods.

**Comment by uschi2000** [comment] 2017-11-03 18:14
closed by https://github.com/palantir/http-remoting/pull/605

**Comment by justinuang** [comment] 2017-11-06 12:10
Thanks! Can we get a release? or is there a way to test a snapshot build

**Comment by dansanduleac** [comment] 2017-11-10 15:44
@uschi2000 should actually close this issue :)

**Closed as completed** 2017-11-10 15:47 UTC

**Comment by justinuang** [comment] 2017-11-13 13:11
Confirmed that this fixes our flakes =) Thanks again!
